version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    #ports:
    #  - "27017:27017"  # Puerto de MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: multimedia
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: multimedia
      ME_CONFIG_MONGODB_URL: mongodb://root:multimedia@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  web-server:
    build: .
    ports:
      - "3000:3000"  # Puerto del Web Server
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:multimedia@mongodb:27017/NMS_MULTIMEDIA_DB ?authSource=admin

volumes:
  mongodb_data: