version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - 80:5173
    volumes:
      - ./frontend/src:/app/src
    networks:
      - multimedia_app
    environment:
      VITE_BACKEND_URI: http://localhost:3000
    depends_on:
      - api

  multimedia_server:
    build: ./node-media-server
    ports: 
      - 8000:8000
      - 1935:1935
    networks:
      - multimedia_app

  api:
    build: ./web-server
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://root:multimedia@db:27017/NMS_MULTIMEDIA_DB?authSource=admin
      NMS_URI: http://multimedia_server:8000
    volumes:
      - ./web-server/src:/app/src
    depends_on:
      - db
      - multimedia_server
    networks:
      - multimedia_app

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: multimedia
    volumes:
      - mongodb_data:/data/db
    networks:
      - multimedia_app

volumes:
  mongodb_data:

networks:
  multimedia_app:
    driver: bridge
