version: '3.8'

services:

  multimedia_server:
    build: ./node-media-server
    ports: 
      - 8000:8000
      - 1935:1935
    volumes:
      - ./node-media-server/index.js:/app/index.js
    networks:
      - multimedia_app

  api:
    build: ./web-server
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://root:multimedia@db:27017/NMS_MULTIMEDIA_DB?authSource=admin
    volumes:
      - ./web-server/src:/app/src
    depends_on:
      - db
    networks:
      - multimedia_app

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: multimedia
    volumes:
      - mongodb_data:/data/db
    networks:
      - multimedia_app

volumes:
  mongodb_data:

networks:
  multimedia_app:
    driver: bridge
