version: '3.8'

services:

  multimedia_server:
    build: ./node-media-server
    ports: 
      - 8000:8000
      - 1935:1935
  
  api:
    build: ./web-server
    ports:
      - 3000:3000
    environment:
      MONGO_URI:: mongodb://db/mongodb_data
    volumes:
      - ./web-server/src:/app/src
    depends_on:
      - db

  db:
    image: mongo:5.0.19-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: multimedia
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  multimedia_app: