version: "3.9"
services:
  media-server:
    container_name: media-server
    build: .
    ports:
      - 8000:8000
      - 1935:1935
    networks:
      - media-server
    volumes:
      - /app/node_modules

networks:
  media-server:
    driver: bridge
    name: media-server



